import { StyleProp, TextStyle } from 'react-native'

export const inner-scroll: StyleProp<TextStyle>
export const white-bg: StyleProp<TextStyle>
export const content-wrapper: StyleProp<TextStyle>
export const sectionTitle: StyleProp<TextStyle>
export const image-uploader: StyleProp<TextStyle>
export const grid: StyleProp<TextStyle>
export const checkbox: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const label: StyleProp<TextStyle>
export const uploadFile: StyleProp<TextStyle>
export const delete: StyleProp<TextStyle>
export const section: StyleProp<TextStyle>
export const pageHead: StyleProp<TextStyle>
export const btn-danger: StyleProp<TextStyle>
export const modal-backdropshow: StyleProp<TextStyle>
export const modal-body: StyleProp<TextStyle>
export const modal-dialog: StyleProp<TextStyle>
export const file-upload: StyleProp<TextStyle>
export const registerTypes: StyleProp<TextStyle>
export const registerTypes__item: StyleProp<TextStyle>
export const registerTypes__item--icon: StyleProp<TextStyle>
export const flex-items: StyleProp<TextStyle>
export const upper_circle: StyleProp<TextStyle>
export const btnbtn-secondary: StyleProp<TextStyle>
export const uploadFile__item: StyleProp<TextStyle>
export const imageAdd: StyleProp<TextStyle>
export const properties: StyleProp<TextStyle>
export const property: StyleProp<TextStyle>
export const overlay: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const propertyFeatures: StyleProp<TextStyle>
export const radio: StyleProp<TextStyle>
export const checked: StyleProp<TextStyle>
export const unchecked: StyleProp<TextStyle>
export const searchAddress: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const map: StyleProp<TextStyle>
export const editProperty: StyleProp<TextStyle>
export const button-row: StyleProp<TextStyle>
export const searchProperty: StyleProp<TextStyle>
export const search-results: StyleProp<TextStyle>
export const search__wrapper: StyleProp<TextStyle>
export const about__wrapper: StyleProp<TextStyle>
export const category: StyleProp<TextStyle>
export const nav-tabs: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const accordion: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const card-header: StyleProp<TextStyle>
export const btn-link: StyleProp<TextStyle>
export const collapsed: StyleProp<TextStyle>
export const content: StyleProp<TextStyle>
export const card-body: StyleProp<TextStyle>
export const faq: StyleProp<TextStyle>
export const bottomTitle: StyleProp<TextStyle>
export const dash-organization: StyleProp<TextStyle>
export const form-group: StyleProp<TextStyle>
export const save-properties: StyleProp<TextStyle>
export const sell-page: StyleProp<TextStyle>
export const card-wrapper: StyleProp<TextStyle>
export const card-button: StyleProp<TextStyle>
export const about: StyleProp<TextStyle>
export const image: StyleProp<TextStyle>
export const statistics: StyleProp<TextStyle>
export const terms_use: StyleProp<TextStyle>
export const contentWrapper: StyleProp<TextStyle>
export const contact_us: StyleProp<TextStyle>
export const left__side: StyleProp<TextStyle>
export const contact: StyleProp<TextStyle>
export const card_position: StyleProp<TextStyle>
export const list-inline: StyleProp<TextStyle>
export const changePassword: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const inline-btn: StyleProp<TextStyle>
export const agent-listing: StyleProp<TextStyle>
export const card-head: StyleProp<TextStyle>
export const agent__info: StyleProp<TextStyle>
export const agent__bio--name: StyleProp<TextStyle>
export const agent__bio--desc: StyleProp<TextStyle>
export const agent__contactInfo: StyleProp<TextStyle>
export const search: StyleProp<TextStyle>
export const d-flex: StyleProp<TextStyle>
export const propertyDetails: StyleProp<TextStyle>
export const banner_heading: StyleProp<TextStyle>
export const banner_heart: StyleProp<TextStyle>
export const banner_content: StyleProp<TextStyle>
export const transparent: StyleProp<TextStyle>
export const text-right: StyleProp<TextStyle>
export const logo: StyleProp<TextStyle>
export const icons: StyleProp<TextStyle>
export const slick-arrow: StyleProp<TextStyle>
export const slick-prev: StyleProp<TextStyle>
export const slick-next: StyleProp<TextStyle>
export const gallery__image: StyleProp<TextStyle>
export const more-items: StyleProp<TextStyle>
export const gallery__image--overlay: StyleProp<TextStyle>
export const heart: StyleProp<TextStyle>
export const paciNo: StyleProp<TextStyle>
export const right-border: StyleProp<TextStyle>
export const contect_items: StyleProp<TextStyle>
export const icon_wrapper: StyleProp<TextStyle>
export const image-wrapper: StyleProp<TextStyle>
export const text-danger: StyleProp<TextStyle>
export const gallery: StyleProp<TextStyle>
export const modal-content: StyleProp<TextStyle>
export const modal-header: StyleProp<TextStyle>
export const slidesCounter: StyleProp<TextStyle>
export const total: StyleProp<TextStyle>
export const current: StyleProp<TextStyle>
export const custom_list: StyleProp<TextStyle>
export const indiviual: StyleProp<TextStyle>
export const propertyListing: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
export const icon): StyleProp<TextStyle>
export const listingTabs: StyleProp<TextStyle>
export const control-label: StyleProp<TextStyle>
export const toggle: StyleProp<TextStyle>
export const float-label: StyleProp<TextStyle>
export const tab-content: StyleProp<TextStyle>
export const agent: StyleProp<TextStyle>
export const toggler-filter: StyleProp<TextStyle>
export const toggle-filter-btn: StyleProp<TextStyle>
export const tab-active: StyleProp<TextStyle>
export const card-wrapper>div: StyleProp<TextStyle>
